### ISSUE TITLE
Versione di Python?

### ISSUE THREAD

**Issue by DarkFighterLuke** [Mikel12455/whafer#3]
Ciao, quale versione di python hai utilizzato?
(Sto lavorando ad alcuni TODO del tuo progetto :) )

**Comment by Mikel12455** [comment]
Se non ricordo male era in Python 3.10, ma dovrebbe andare anche con versioni più recenti

**Comment by DarkFighterLuke** [comment]
Grazie, con 3.9 e 3.10 sono riuscito a farlo partire
